#include "watchdog.h"
#include "main.h"


extern IWDG_HandleTypeDef hiwdg;


WATCHDOG_Status_t WATCHDOG_Init(void)
{
    /*
     * The hardware IWDG is configured and started by
     * MX_IWDG_Init() generated by STM32CubeMX.
     *
     * No additional hardware initialization is required here.
     */
    return WATCHDOG_OK;
}


WATCHDOG_Status_t WATCHDOG_Refresh(void)
{
    if (HAL_IWDG_Refresh(&hiwdg) != HAL_OK)
    {
        return WATCHDOG_ERROR;
    }

    return WATCHDOG_OK;
}